package io.openems.edge.meter.scheco;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.common.types.MeterType;

@ObjectClassDefinition(name = "Meter Scheco", description = "Reads one sub-meter from the Scheco Modbus/TCP gateway.")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "Grid, Production, Consumption. Defaults to Consumption (metered).")
	MeterType type() default MeterType.CONSUMPTION_METERED;

	@AttributeDefinition(name = "Sub-Meter", description = "Which sub-meter of the gateway to read")
	SubMeter meter() default SubMeter.MAIN_CONTROL;

	@AttributeDefinition(name = "Modbus-ID", description = "Id of the modbus bridge")
	String modbus_id() default "modbus0";

	@AttributeDefinition(name = "Modbus Unit-ID", description = "The Unit-ID of the Modbus gateway")
	int modbusUnitId() default 10;

	@AttributeDefinition(name = "Invert", description = "Should the power value be inverted?")
	boolean invert() default false;

	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "Meter Scheco [{id}]";

}
